/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kgdsoftware.bible;

import com.kgdsoftware.bible.model.Note;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author henriwarren
 */
public class NoteList extends javax.swing.JFrame {
    private Note mNote;
    
    /**
     * Creates new form NoteList
     */
    public NoteList() {
        initComponents();
        noteList.setCellRenderer(new NoteDetailRenderer());
        idLabel.setText("none selected");
        displayNoteList();
        mNote = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        noteList = new javax.swing.JList<Note>();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        noteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noteListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(noteList);

        noteText.setColumns(20);
        noteText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        noteText.setLineWrap(true);
        noteText.setRows(5);
        noteText.setTabSize(2);
        noteText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(noteText);

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("info");

        refreshButton.setText("Refresh");
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(deleteButton)
            .addComponent(refreshButton)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteListMouseClicked
        int i = noteList.getSelectedIndex();
        ListModel model = noteList.getModel();
        mNote = (Note)model.getElementAt(i);
        noteText.setText(mNote.queryText());
        idLabel.setText("id: " + mNote.getId());
    }//GEN-LAST:event_noteListMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        if(mNote != null) {
            System.out.println("deleteButtonMouseClicked\n" + mNote);
            mNote.delete();
            noteText.setText("");
            noteList.setModel(Note.query());
            idLabel.setText("none selected");
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked

        noteList.setModel(Note.query());
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void displayNoteList() {
        SwingUtilities.invokeLater(()-> {
            noteList.setModel(Note.query());
        });
    }
    
    public static class NoteDetailRenderer extends JPanel implements ListCellRenderer<Note> {
        @Override
        public Component getListCellRendererComponent(JList<? extends Note> list, Note note, int index, boolean isSelected, boolean cellHasFocus) {
            NoteDetailCell cell = new NoteDetailCell();
            cell.setId(note.getId());
            cell.setLocalTime(note.getLocalTimestamp());
            cell.setRemoteTime(note.getRemoteTimestamp());
            cell.setVerse(note.getBookId(), note.getChapter(), note.getVerse());
            cell.setVerseId(note.getVerseId());
            cell.setChecked(note.isPosted());
            cell.setChanged(note.isConfirmed());
            return cell;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Note> noteList;
    private javax.swing.JTextArea noteText;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
